package hu.codeandsoda.osa.util;


public enum ErrorCode {

    USER_EXISTS,
    USER_NOT_SAVED,
    USER_NOT_FOUND,
    USER_DISABLED,
    USER_ALREADY_ENABLED,
    INVALID_USER,
    USER_DELETE_ERROR,
    ANONYMOUS_USER_NOT_FOUND,

    REGISTRATION_ERROR,
    CONFIRM_REGISTRATION_ERROR,
    SUBMIT_FORGOTTEN_PASSWORD_REQUEST_ERROR,
    RESET_PASSWORD_ERROR,
    CHANGE_PASSWORD_ERROR,
    
    INVALID_REGISTRATION_DATA,
    INVALID_TOKEN,
    INVALID_PASSWORD,
    INVALID_NEW_PASSWORD,
    PASSWORDS_DO_NOT_MATCH,
    INVALID_PASSWORD_LENGTH,

    MEDIA_UPLOAD_ERROR,
    MEDIA_LOADING_ERROR,

    INVALID_MEDIA_CONTENT_TYPE,
    INVALID_SORT_DIRECTION,
    INVALID_SORT_BY_FIELD,
    INVALID_PAGE,
    INVALID_PAGE_SIZE,
    INVALID_IMAGE_ID,
    INVALID_DOCUMENT_IMAGE_INDEX,
    INVALID_IMAGE_ROTATION_VALUE,
    INVALID_DOCUMENT_PERIOD_VALUE,
    EDIT_IMAGE_NAME_ERROR,
    IMAGE_NAME_EMPTY,
    IMAGE_NOT_FOUND,
    DELETE_IMAGE_ERROR,

    AWS_S3_CONNECTION_ERROR,
    AWS_S3_MULTIPLE_OBJECT_DELETE_ERROR,
    AWS_S3_KEY_ENCODING_ERROR,

    DOCUMENT_NOT_FOUND,
    INVALID_DOCUMENT_IMAGE_ID,
    INVALID_DOCUMENT_HASH,
    GENERATE_OCR_ERROR,
    IPFS_UPLOAD_ERROR,

    DOCUMENT_ALREADY_PUBLISHED,
    HASH_DOCUMENT_ERROR,
    CREATE_PDF_ERROR,
    DOCUMENT_HAS_NO_IMAGES,
    MISSING_DOCUMENT_METADATA_FIELD,
    MISSING_PUBLISHED_DOCUMENT_FIELD,
    INVALID_PUBLISHED_DOCUMENT_FIELD,

    INVALID_COLLECTION_NAME,
    INVALID_COLLECTION_ID,
    COLLECTION_CONTAINS_DOCUMENT,
    PUBLISHED_DOCUMENT_NOT_FOUND,

    PUBLISH_IN_PROGRESS;
}
